# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-05-25 04:44
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Game',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('board11', models.CharField(max_length=1)),
                ('board12', models.CharField(max_length=1)),
                ('board21', models.CharField(max_length=1)),
                ('board22', models.CharField(max_length=1)),
            ],
        ),
    ]
