# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-05-27 07:48
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='game',
            name='board11',
        ),
        migrations.RemoveField(
            model_name='game',
            name='board12',
        ),
        migrations.RemoveField(
            model_name='game',
            name='board21',
        ),
        migrations.RemoveField(
            model_name='game',
            name='board22',
        ),
        migrations.AddField(
            model_name='game',
            name='f_col',
            field=models.CharField(default='0', max_length=1),
        ),
        migrations.AddField(
            model_name='game',
            name='f_row',
            field=models.CharField(default='0', max_length=1),
        ),
        migrations.AddField(
            model_name='game',
            name='t_col',
            field=models.CharField(default='0', max_length=1),
        ),
        migrations.AddField(
            model_name='game',
            name='t_row',
            field=models.CharField(default='0', max_length=1),
        ),
        migrations.AddField(
            model_name='game',
            name='turn',
            field=models.CharField(default='1', max_length=1),
        ),
    ]
