# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-05-30 14:19
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0002_auto_20170527_0748'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='game',
            name='f_col',
        ),
        migrations.RemoveField(
            model_name='game',
            name='f_row',
        ),
        migrations.RemoveField(
            model_name='game',
            name='t_col',
        ),
        migrations.RemoveField(
            model_name='game',
            name='t_row',
        ),
        migrations.AddField(
            model_name='game',
            name='from_id',
            field=models.CharField(default='0', max_length=2),
        ),
        migrations.AddField(
            model_name='game',
            name='to_id',
            field=models.CharField(default='0', max_length=2),
        ),
        migrations.AlterField(
            model_name='game',
            name='turn',
            field=models.CharField(default='white', max_length=5),
        ),
    ]
